<robot name="base" xmlns:xacro="http://wiki.ros.org/xacro">
    <xacro:include filename="scara.xacro" />

    <link name="world" />

    <joint name="base_to_world" type="fixed">
        <parent link="world" />
        <child link="base_link" />
        <origin xyz="0.0 0.0 ${base_link_z/2}" />
    </joint>

    <gazebo reference="base_link">
        <material>Gazebo/Red</material>
    </gazebo>

    <gazebo reference="link1">
        <material>Gazebo/Green</material>
    </gazebo>

    <gazebo reference="link2">
        <material>Gazebo/Blue</material>
    </gazebo>

    <gazebo reference="link3">
        <material>Gazebo/Yellow</material>
    </gazebo>

    <gazebo reference="gripper_base_link">
        <material>Gazebo/Red</material>
    </gazebo>

    <gazebo reference="gripper_left">
        <material>Gazebo/Green</material>
    </gazebo>

    <gazebo reference="gripper_right">
        <material>Gazebo/Blue</material>
    </gazebo>

    <gazebo>
        <plugin name="gazebo_ros_control" filename="libgazebo_ros_control.so">
            <robotNamespace>/scara_robot</robotNamespace>
        </plugin>
    </gazebo>
</robot>