<robot name="base" xmlns:xacro="http://wiki.ros.org/xacro">
    <xacro:include filename="scara.xacro" />

    <link name="world" />

    <joint name="base_2_world" type="fixed">
        <parent link="world" />
        <child link="base_link" />
        <origin xyz="0.0 0.0 ${base_link_z/2}" />
    </joint>

    <gazebo reference="base_link">
        <material>Gazebo/Red</material>
    </gazebo>

    <gazebo reference="link1">
        <material>Gazebo/Green</material>
    </gazebo>

    <gazebo reference="link2">
        <material>Gazebo/Blue</material>
    </gazebo>

    <gazebo reference="link3">
        <material>Gazebo/Yellow</material>
    </gazebo>

    <gazebo reference="gripper_base_link">
        <material>Gazebo/Red</material>
    </gazebo>

    <gazebo reference="gripper_left">
        <material>Gazebo/Green</material>
    </gazebo>

    <gazebo reference="gripper_right">
        <material>Gazebo/Blue</material>
    </gazebo>

    <gazebo>
        <plugin name="gazebo_ros_control" filename="libgazebo_ros_control.so">
            <robotNamespace>/rrbot</robotNamespace>
        </plugin>
    </gazebo>

    <transmission name="tran1">
        <type>transmission_interface/SimpleTransmission</type>
        <joint name="link12base">
            <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
        </joint>
        <actuator name="motor1">
            <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
            <mechanicalReduction>1</mechanicalReduction>
        </actuator>
    </transmission>

    <transmission name="tran2">
        <type>transmission_interface/SimpleTransmission</type>
        <joint name="link2_to_link1">
            <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
        </joint>
        <actuator name="motor2">
            <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
            <mechanicalReduction>1</mechanicalReduction>
        </actuator>
    </transmission>

    <transmission name="tran3">
        <type>transmission_interface/SimpleTransmission</type>
        <joint name="link3_to_link2">
            <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
        </joint>
        <actuator name="motor3">
            <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
            <mechanicalReduction>1</mechanicalReduction>
        </actuator>
    </transmission>

    <transmission name="tran4">
        <type>transmission_interface/SimpleTransmission</type>
        <joint name="gripper_base_link_to_link3">
            <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
        </joint>
        <actuator name="motor4">
            <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
            <mechanicalReduction>1</mechanicalReduction>
        </actuator>
    </transmission>

    <transmission name="tran5">
        <type>transmission_interface/SimpleTransmission</type>
        <joint name="left_2_gripper_base">
            <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
        </joint>
        <actuator name="motor5">
            <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
            <mechanicalReduction>1</mechanicalReduction>
        </actuator>
    </transmission>

    <transmission name="tran6">
        <type>transmission_interface/SimpleTransmission</type>
        <joint name="right_2_gripper_base">
            <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
        </joint>
        <actuator name="motor6">
            <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
            <mechanicalReduction>1</mechanicalReduction>
        </actuator>
    </transmission>
</robot>