controller_manager:
  ros__parameters:
  update_rate: 30
  use_sim_time: true

  # Publish all joint states -----------------------------------
  joint_state_broadcast:
    type: joint_state_broadcaster/JointStateBroadcaster 
    publish_rate: 50  

  # Position Controllers ---------------------------------------
  joint_position_controller:
    type: position_controllers/JointGroupPositionController

joint_position_controller:
  ros__parameters:
    joints:
      - link1_to_base
      - link2_to_link1
      - link3_to_link2
      - gripper_base_link_to_link3
      - left_to_gripper_base
      - right_to_gripper_base